name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: ğŸ–¥ï¸ Install xvfb
        run: sudo apt-get install -y xvfb

      - name: ğŸ­ Setup Playwright
        uses: microsoft/playwright-github-action@v1

      - name: ğŸ“¥ Install dependencies
        run: npm install

      - name: ğŸ—ï¸ Build
        run: npm run build

      - name: ğŸ“‚ List build output
        run: ls -l dist

      - name: ğŸŒ Install Playwright browsers
        run: npx playwright install --with-deps

      - name: ğŸ“¦ Install pnpm
        run: npm install -g pnpm

      - name: ğŸ” Type check
        run: npm run type-check

      - name: ğŸ§¹ Lint
        run: npm run lint

      - name: ğŸ§ª Run unit tests
        run: npm run test

      - name: ğŸš€ Run end-to-end tests
        run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' npm run test:e2e:concurrently
        env:
          DEBUG: pw:api
          VITE_APP_TITLE: ${{ secrets.VITE_APP_TITLE }}
          TEST_BASE_URL: 'http://localhost:3001'

      - name: ğŸ–¥ï¸ Start server
        run: npm run start-server & sleep 5

      - name: ğŸš¦ Run Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: 'http://localhost:3001'
          uploadArtifacts: true

      - name: ğŸš€ Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
